version: '3.8'

services:
  sqlserver:
    build: ./database
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Heslo.123"
      ACCEPT_EULA: "Y"
      INIT_DATABASE: true

  # api:
    # image: api
    # build:
      # context: .
      # dockerfile: api/Dockerfile
    # ports:
      # - 5263:5263
      # - 5281:5281
      # - 1668:1668
      # - 7170:7170
    # depends_on:
      # - sql_server
